version: "3"

services:
  frappe-lms:
    image: frappe/bench:latest
    command: bash /workspace/dokploy/init.sh
    environment:
      - SHELL=/bin/bash
      - ADMIN_PASSWORD
      - MARIADB_ROOT_PASSWORD
      - REDIS_QUEUE_HOST
      - REDIS_CACHE_HOST
      - REDIS_SOCKETIO_HOST
      - MARIADB_HOST
    working_dir: /home/frappe
    volumes:
      - .:/workspace
    ports:
      - 8000:8000
      - 9000:9000
    restart: always
    networks:
      - dokploy-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.frappe-lms.rule=Host(`frappe-lms.dokploy.com`)
      - traefik.http.routers.frappe-lms.entrypoints=websecure
      - traefik.http.routers.frappe-lms.tls.certResolver=letsencrypt
      - traefik.http.services.frappe-lms.loadbalancer.server.port=8000
  # Add more containers below (nginx, postgres, etc.)
# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  dokploy-network:
    external: true